import { claimsFromInputs, detectConflicts } from "./conflict-detector";
import { FIELD_KEYS } from "./constants";
import { normalizeAddress } from "./normalize-address";
import { summarizeResearch } from "./report-summarizer";
import type { NormalizedResearchResult, PropertyFact, ReportSource } from "./schemas";
import type { ClaimInput } from "./types";
import { sleep } from "@/lib/utils";

const MOCK_APN = "47222019";
const NOW = () => new Date().toISOString();

function buildClaims(_retrievedAt: string): ClaimInput[] {
  return [
    {
      fieldKey: FIELD_KEYS.apn,
      fieldLabel: "APN",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.sccassessor.org/property-profile/47222019?sample=1",
      rawValue: MOCK_APN,
      normalizedValue: MOCK_APN,
      matchMethod: "mock",
      confidence: "high",
      sourceUpdatedAt: "2024-11-12T00:00:00.000Z",
    },
    {
      fieldKey: FIELD_KEYS.apn,
      fieldLabel: "APN",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.attomdata.com/property/655-13th-st?sample=1",
      rawValue: MOCK_APN,
      normalizedValue: MOCK_APN,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.lotSqFt,
      fieldLabel: "Lot size",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.sccassessor.org/property-profile/47222019?sample=1",
      rawValue: "6000",
      normalizedValue: "6000",
      numericValue: 6000,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.lotSqFt,
      fieldLabel: "Lot size",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.attomdata.com/property/655-13th-st?sample=1",
      rawValue: "6250",
      normalizedValue: "6250",
      numericValue: 6250,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.livingAreaSqFt,
      fieldLabel: "Living area",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.sccassessor.org/property-profile/47222019?sample=1",
      rawValue: "1248",
      normalizedValue: "1248",
      numericValue: 1248,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.livingAreaSqFt,
      fieldLabel: "Living area",
      sourceName: "RentCast (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.rentcast.io/properties/655-13th-st?sample=1",
      rawValue: "1350",
      normalizedValue: "1350",
      numericValue: 1350,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.bedrooms,
      fieldLabel: "Bedrooms",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "3",
      normalizedValue: "3",
      numericValue: 3,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.bathrooms,
      fieldLabel: "Bathrooms",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "1",
      normalizedValue: "1",
      numericValue: 1,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.stories,
      fieldLabel: "Stories",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "1",
      normalizedValue: "1",
      numericValue: 1,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.yearBuilt,
      fieldLabel: "Year built",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "1939",
      normalizedValue: "1939",
      numericValue: 1939,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.propertyType,
      fieldLabel: "Property type",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "Single Family Residential",
      normalizedValue: "Single Family Residential",
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.estimatedValue,
      fieldLabel: "Estimated value",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "1180000",
      normalizedValue: "1180000",
      numericValue: 1_180_000,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.estimatedValue,
      fieldLabel: "Estimated value",
      sourceName: "RentCast (mock)",
      sourceType: "mock",
      rawValue: "1125000",
      normalizedValue: "1125000",
      numericValue: 1_125_000,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.assessedValue,
      fieldLabel: "Assessed value",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "412500",
      normalizedValue: "412500",
      numericValue: 412_500,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.lastSaleDate,
      fieldLabel: "Last sale date",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "2014-06-18",
      normalizedValue: "2014-06-18",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.lastSalePrice,
      fieldLabel: "Last sale price",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "685000",
      normalizedValue: "685000",
      numericValue: 685_000,
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.ownerName,
      fieldLabel: "Owner name",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "Sample Owner Trust",
      normalizedValue: "Sample Owner Trust",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.ownerMailingAddress,
      fieldLabel: "Owner mailing address",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "655 13th St, San Jose, CA 95112",
      normalizedValue: "655 13th St, San Jose, CA 95112",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.subdivision,
      fieldLabel: "Subdivision",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "Hensley Addition",
      normalizedValue: "Hensley Addition",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.tractNumber,
      fieldLabel: "Tract number",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "Tract 512",
      normalizedValue: "Tract 512",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.taxRateArea,
      fieldLabel: "Tax rate area",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "17194",
      normalizedValue: "17194",
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.zoning,
      fieldLabel: "Zoning",
      sourceName: "San Jose Planning (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.sanjoseca.gov/zoning?sample=1",
      rawValue: "R-1-8",
      normalizedValue: "R-1-8",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.generalPlan,
      fieldLabel: "General Plan",
      sourceName: "San Jose Planning (mock)",
      sourceType: "mock",
      rawValue: "No general plan designation found",
      normalizedValue: "No general plan designation found",
      matchMethod: "mock",
      confidence: "low",
    },
    {
      fieldKey: FIELD_KEYS.historicStatus,
      fieldLabel: "Historic status",
      sourceName: "San Jose Historic Resources (mock)",
      sourceType: "mock",
      rawValue: "Not designated (mock)",
      normalizedValue: "Not designated (mock)",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.floodZone,
      fieldLabel: "Flood zone",
      sourceName: "FEMA (mock)",
      sourceType: "mock",
      sourceUrl: "https://msc.fema.gov/portal/search?sample=1",
      rawValue: "X (Area of Minimal Flood Hazard)",
      normalizedValue: "X (Area of Minimal Flood Hazard)",
      matchMethod: "mock",
      confidence: "medium",
    },
    {
      fieldKey: FIELD_KEYS.fireZone,
      fieldLabel: "Fire zone",
      sourceName: "CAL FIRE (mock)",
      sourceType: "mock",
      sourceUrl:
        "https://osfm.fire.ca.gov/what-we-do/community-wildfire-preparedness-and-mitigation/fire-hazard-severity-zones",
      rawValue: null,
      normalizedValue: null,
      matchMethod: "mock",
      confidence: "unavailable",
    },
    {
      fieldKey: FIELD_KEYS.latitude,
      fieldLabel: "Latitude",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "37.34521",
      normalizedValue: "37.34521",
      numericValue: 37.34521,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.longitude,
      fieldLabel: "Longitude",
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      rawValue: "-121.88045",
      normalizedValue: "-121.88045",
      numericValue: -121.88045,
      matchMethod: "mock",
      confidence: "high",
    },
    {
      fieldKey: FIELD_KEYS.buildingCount,
      fieldLabel: "Building count",
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      rawValue: "1",
      normalizedValue: "1",
      numericValue: 1,
      matchMethod: "mock",
      confidence: "medium",
    },
  ];
}

function preferredFact(
  category: string,
  fieldKey: string,
  fieldLabel: string,
  text: string | null,
  number: number | null,
  sourceName: string,
  sourceUrl: string | null,
  confidence: PropertyFact["confidence"],
  unit?: string | null,
): PropertyFact {
  return {
    category,
    fieldKey,
    fieldLabel,
    normalizedValueText: text,
    normalizedValueNumber: number,
    normalizedValueBoolean: null,
    unit: unit ?? null,
    preferredSourceName: sourceName,
    preferredSourceUrl: sourceUrl,
    confidence,
  };
}

export async function runMockPropertyResearch(
  inputAddress: string,
): Promise<NormalizedResearchResult> {
  // Artificial delay so the processing UI can show progress (2–4 seconds).
  await sleep(2500);

  const normalized = normalizeAddress(inputAddress);
  const retrievedAt = NOW();
  const claimInputs = buildClaims(retrievedAt);
  const claims = claimsFromInputs(claimInputs, retrievedAt);
  const conflicts = detectConflicts(claims);

  const countyProfileUrl =
    "https://example.sccassessor.org/property-profile/47222019?sample=1&note=placeholder-link";
  const parcelGisUrl = "https://example.scc-gis.org/parcel/47222019?sample=1&note=placeholder-link";
  const tractMapUrl =
    "https://example.sccassessor.org/tract-maps/512?sample=1&note=placeholder-link";
  const assessorUrl =
    "https://example.sccassessor.org/search?apn=47222019&sample=1&note=placeholder-link";
  const zoningMapUrl =
    "https://example.sanjoseca.gov/planning/zoning-map?lat=37.34521&lng=-121.88045&sample=1";
  const permitSearchUrl =
    "https://example.sanjoseca.gov/permits/search?address=655%2013th%20St&sample=1";

  const facts: PropertyFact[] = [
    preferredFact(
      "identity",
      FIELD_KEYS.apn,
      "APN",
      MOCK_APN,
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.lotSqFt,
      "Lot size",
      "6000",
      6000,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
      "sq ft",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.livingAreaSqFt,
      "Living area",
      "1248",
      1248,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
      "sq ft",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.bedrooms,
      "Bedrooms",
      "3",
      3,
      "ATTOM (mock)",
      null,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.bathrooms,
      "Bathrooms",
      "1",
      1,
      "ATTOM (mock)",
      null,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.stories,
      "Stories",
      "1",
      1,
      "ATTOM (mock)",
      null,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.yearBuilt,
      "Year built",
      "1939",
      1939,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.propertyType,
      "Property type",
      "Single Family Residential",
      null,
      "ATTOM (mock)",
      null,
      "high",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.estimatedValue,
      "Estimated value",
      "1180000",
      1_180_000,
      "ATTOM (mock)",
      null,
      "medium",
      "USD",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.assessedValue,
      "Assessed value",
      "412500",
      412_500,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
      "USD",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.lastSaleDate,
      "Last sale date",
      "2014-06-18",
      null,
      "ATTOM (mock)",
      null,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.lastSalePrice,
      "Last sale price",
      "685000",
      685_000,
      "ATTOM (mock)",
      null,
      "medium",
      "USD",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.ownerName,
      "Owner name",
      "Sample Owner Trust",
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.ownerMailingAddress,
      "Owner mailing address",
      "655 13th St, San Jose, CA 95112",
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.subdivision,
      "Subdivision",
      "Hensley Addition",
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.tractNumber,
      "Tract number",
      "Tract 512",
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "medium",
    ),
    preferredFact(
      "characteristics",
      FIELD_KEYS.taxRateArea,
      "Tax rate area",
      "17194",
      null,
      "Santa Clara County Assessor (mock)",
      countyProfileUrl,
      "high",
    ),
    preferredFact(
      "planning",
      FIELD_KEYS.zoning,
      "Zoning",
      "R-1-8",
      null,
      "San Jose Planning (mock)",
      zoningMapUrl,
      "medium",
    ),
    preferredFact(
      "planning",
      FIELD_KEYS.generalPlan,
      "General Plan",
      "No general plan designation found",
      null,
      "San Jose Planning (mock)",
      null,
      "low",
    ),
    preferredFact(
      "planning",
      FIELD_KEYS.historicStatus,
      "Historic status",
      "Not designated (mock)",
      null,
      "San Jose Historic Resources (mock)",
      null,
      "medium",
    ),
    preferredFact(
      "planning",
      FIELD_KEYS.floodZone,
      "Flood zone",
      "X (Area of Minimal Flood Hazard)",
      null,
      "FEMA (mock)",
      "https://msc.fema.gov/portal/search?sample=1",
      "medium",
    ),
    preferredFact(
      "planning",
      FIELD_KEYS.fireZone,
      "Fire zone",
      null,
      null,
      "CAL FIRE (mock)",
      null,
      "unavailable",
    ),
  ];

  const parcelGeometry = {
    type: "Polygon",
    coordinates: [
      [
        [-121.8807, 37.34505],
        [-121.8802, 37.34505],
        [-121.8802, 37.34538],
        [-121.8807, 37.34538],
        [-121.8807, 37.34505],
      ],
    ],
  };

  const sources: ReportSource[] = [
    {
      sourceName: "Santa Clara County Assessor (mock)",
      sourceType: "mock",
      sourceUrl: countyProfileUrl,
      status: "active",
      retrievedAt,
      sourceUpdatedAt: "2024-11-12T00:00:00.000Z",
      responseTimeMs: 210,
      statusMessage: "Mock county property profile data for Phase 1.",
    },
    {
      sourceName: "ATTOM (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.attomdata.com/property/655-13th-st?sample=1",
      status: "active",
      retrievedAt,
      sourceUpdatedAt: "2025-01-08T00:00:00.000Z",
      responseTimeMs: 340,
      statusMessage: "Mock ATTOM payload. Not a live licensed API response.",
    },
    {
      sourceName: "RentCast (mock)",
      sourceType: "mock",
      sourceUrl: "https://example.rentcast.io/properties/655-13th-st?sample=1",
      status: "active",
      retrievedAt,
      sourceUpdatedAt: "2025-01-05T00:00:00.000Z",
      responseTimeMs: 290,
      statusMessage: "Mock RentCast payload. Not a live API response.",
    },
    {
      sourceName: "San Jose Planning (mock)",
      sourceType: "mock",
      sourceUrl: zoningMapUrl,
      status: "manual_review",
      retrievedAt,
      sourceUpdatedAt: null,
      responseTimeMs: 180,
      statusMessage: "Mock planning values require manual confirmation with city GIS in Prompt 2.",
    },
    {
      sourceName: "FEMA (mock)",
      sourceType: "mock",
      sourceUrl: "https://msc.fema.gov/portal/search?sample=1",
      status: "active",
      retrievedAt,
      sourceUpdatedAt: null,
      responseTimeMs: 260,
      statusMessage: "Mock FEMA flood designation for Phase 1.",
    },
    {
      sourceName: "CAL FIRE (mock)",
      sourceType: "mock",
      sourceUrl:
        "https://osfm.fire.ca.gov/what-we-do/community-wildfire-preparedness-and-mitigation/fire-hazard-severity-zones",
      status: "unavailable",
      retrievedAt,
      sourceUpdatedAt: null,
      responseTimeMs: null,
      statusMessage: "Optional fire-zone source unavailable in this mock run.",
    },
  ];

  const resultWithoutSummary: Omit<NormalizedResearchResult, "summary"> = {
    identity: {
      inputAddress: normalized.inputAddress,
      standardizedAddress: "655 13th St, San Jose, CA 95112",
      apn: MOCK_APN,
      attomId: "MOCK-ATTOM-65513",
      latitude: 37.34521,
      longitude: -121.88045,
      jurisdiction: "San Jose",
      jurisdictionType: "incorporated city",
      county: "Santa Clara",
      state: "CA",
      zipCode: "95112",
    },
    characteristics: {
      propertyType: "Single Family Residential",
      lotSquareFootage: 6000,
      livingAreaSquareFootage: 1248,
      bedrooms: 3,
      bathrooms: 1,
      stories: 1,
      yearBuilt: 1939,
      buildingCount: 1,
      existingStructures:
        "Primary residence; possible small detached shed (unverified mock observation)",
      estimatedValue: 1_180_000,
      assessedValue: 412_500,
      lastSaleDate: "2014-06-18",
      lastSalePrice: 685_000,
      ownerName: "Sample Owner Trust",
      ownerMailingAddress: "655 13th St, San Jose, CA 95112",
      subdivision: "Hensley Addition",
      tractNumber: "Tract 512",
      taxRateArea: "17194",
    },
    planning: {
      zoning: "R-1-8",
      generalPlanDesignation: "No general plan designation found",
      jurisdictionType: "incorporated San Jose",
      relevantOverlays: [
        "Airport Influence Area (mock sample)",
        "Hydrology review area (mock sample)",
      ],
      historicDesignation: "Not designated (mock)",
      floodZone: "X (Area of Minimal Flood Hazard)",
      fireZone: null,
    },
    maps: {
      parcelMapUrl: parcelGisUrl,
      countyPropertyProfileReportUrl: countyProfileUrl,
      tractMapUrl,
      assessorUrl,
      zoningMapUrl,
      permitSearchUrl,
      redfinUrl: "https://www.redfin.com/CA/San-Jose/655-13th-St-95112/sample-link",
      googleMapsUrl:
        "https://www.google.com/maps/search/?api=1&query=655+13th+St,+San+Jose,+CA+95112",
      streetViewUrl:
        "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=37.34521,-121.88045",
      femaUrl: "https://msc.fema.gov/portal/search?sample=1",
      fireZoneUrl:
        "https://osfm.fire.ca.gov/what-we-do/community-wildfire-preparedness-and-mitigation/fire-hazard-severity-zones",
    },
    permits: [
      {
        permitNumber: "BLD-2018-SAMPLE",
        description: "Interior remodel (mock sample permit)",
        status: "Final",
        appliedDate: "2018-03-02",
        issuedDate: "2018-04-10",
        finalDate: "2018-09-22",
        sourceUrl: permitSearchUrl,
      },
    ],
    facts,
    claims,
    conflicts,
    sources,
    parcelGeometry: {
      geometryGeojson: parcelGeometry,
      centroidLatitude: 37.34521,
      centroidLongitude: -121.88045,
      calculatedAreaSqFt: 5980,
      sourceName: "Santa Clara County GIS (mock)",
      sourceUrl: parcelGisUrl,
    },
    siteObservations: [
      {
        observationType: "main_house_placement",
        title: "Main house placement",
        description:
          "Primary residence appears centered on the front half of the parcel with usable rear yard depth (preliminary imagery review).",
        confidence: "low",
        sourceName: "Visual observation (mock)",
        sourceUrl:
          "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=37.34521,-121.88045",
      },
      {
        observationType: "rear_yard",
        title: "Approximate rear-yard area",
        description:
          "Rear yard appears roughly 1,800–2,200 sq ft based on mock parcel geometry; not a measured survey.",
        confidence: "low",
        sourceName: "Visual observation (mock)",
      },
      {
        observationType: "detached_structures",
        title: "Detached structures",
        description:
          "Possible small shed or accessory structure near the rear fence line (unverified).",
        confidence: "low",
        sourceName: "Visual observation (mock)",
      },
      {
        observationType: "trees",
        title: "Tree coverage",
        description:
          "Mature trees along the rear and one side yard may affect ADU placement and access.",
        confidence: "low",
        sourceName: "Visual observation (mock)",
      },
      {
        observationType: "access",
        title: "Possible access constraints",
        description:
          "Side-yard clearance looks narrow on one side; confirm driveway and utility access on site.",
        confidence: "low",
        sourceName: "Visual observation (mock)",
      },
    ],
    pemPreparation: {
      overview:
        "This San Jose R-1-8 lot is a compact older single-family parcel with enough mock rear-yard depth to discuss ADU concepts, but lot-size and living-area source disagreements should be clarified early in the PEM.",
      propertyFindings: [
        "County assessor (mock) shows approximately 6,000 sq ft lot area and 1939 year built.",
        "Licensed mock sources disagree on living area (1,248 vs 1,350 sq ft) and lot size (6,000 vs 6,250 sq ft).",
        "Fire-zone data was unavailable in this mock run; flood zone is reported as FEMA X.",
      ],
      propertyQuestions: [
        "Has the homeowner completed any additions or conversions that might explain the living-area mismatch?",
        "Is there an existing accessory structure that must remain, or can it be removed for ADU placement?",
        "Are there known easements, shared driveways, or HOA restrictions not visible in public records?",
        "What is the preferred ADU use (rental, multigenerational, or office) and parking preference?",
      ],
      verifyDuringPem: [
        "Walk rear and side yards and note clearances from fences and trees.",
        "Confirm owner goals, timeline, and any prior ADU conversations with the city.",
        "Photograph possible utility meters and sewer cleanouts if visible.",
      ],
      verifyDuringFeasibility: [
        "Measure setbacks and usable rear-yard area against San Jose ADU standards.",
        "Reconcile living-area and lot-size conflicts with on-site measurements.",
        "Check driveway and parking configuration against municipal requirements.",
      ],
      verifyThroughTitleOrSurvey: [
        "Confirm APN 47222019 and legal description.",
        "Identify easements that could constrain ADU footprint or access.",
        "Validate parcel boundary against the mock GIS polygon with a survey if needed.",
      ],
      verifyWithPlanning: [
        "Confirm R-1-8 zoning and any overlays on the official city map.",
        "Ask whether historic review is required despite the mock non-designation.",
        "Confirm permit search process and any open code cases.",
      ],
    },
  };

  // Informational conflict for unavailable optional source when fire zone is missing
  if (!resultWithoutSummary.planning.fireZone) {
    conflicts.push({
      fieldKey: FIELD_KEYS.fireZone,
      fieldLabel: "Fire zone",
      severity: "information",
      description: "CAL FIRE fire-zone source was unavailable; field remains missing.",
      values: [
        {
          sourceName: "CAL FIRE (mock)",
          value: "unavailable",
          sourceUrl:
            "https://osfm.fire.ca.gov/what-we-do/community-wildfire-preparedness-and-mitigation/fire-hazard-severity-zones",
        },
      ],
      recommendedResolution:
        "Check CAL FIRE hazard maps manually before the PEM if wildfire risk is a concern.",
    });
  }

  const summary = summarizeResearch({ ...resultWithoutSummary, conflicts });

  return {
    ...resultWithoutSummary,
    conflicts,
    summary,
  };
}
