export type AttomRequestResult<T> = {
  data: T;
  responseTimeMs: number;
  httpStatus: number;
  packagePath: string;
  unavailable?: boolean;
  statusMessage?: string;
};

export type AttomPropertyIdentity = {
  attomId: string | null;
  apn: string | null;
  originalApn: string | null;
  fips: string | null;
  oneLineAddress: string | null;
  addressLine1: string | null;
  locality: string | null;
  county: string | null;
  state: string | null;
  zipCode: string | null;
  latitude: number | null;
  longitude: number | null;
  matchCode: string | null;
  publicationDate: string | null;
  lastModified: string | null;
};

export type AttomNormalizedProperty = {
  identity: AttomPropertyIdentity;
  propertyType: string | null;
  propertySubtype: string | null;
  landUseCode: string | null;
  lotAcres: number | null;
  lotSquareFootage: number | null;
  livingAreaSquareFootage: number | null;
  grossAreaSquareFootage: number | null;
  bedrooms: number | null;
  bathroomsFull: number | null;
  bathroomsPartial: number | null;
  bathroomsTotal: number | null;
  stories: number | null;
  yearBuilt: number | null;
  buildingCount: number | null;
  pool: boolean | null;
  constructionType: string | null;
  foundationType: string | null;
  roofType: string | null;
  heating: string | null;
  cooling: string | null;
  garage: string | null;
  legalDescription: string | null;
  subdivision: string | null;
  block: string | null;
  tract: string | null;
  assessedValueTotal: number | null;
  assessedValueLand: number | null;
  assessedValueImprovement: number | null;
  taxAmount: number | null;
  assessmentYear: number | null;
  taxYear: number | null;
  estimatedValue: number | null;
  estimatedValueLow: number | null;
  estimatedValueHigh: number | null;
  avmConfidence: number | null;
  avmDate: string | null;
  lastSaleDate: string | null;
  lastSaleAmount: number | null;
  recordingDate: string | null;
  documentNumber: string | null;
  documentType: string | null;
  ownerNames: string | null;
  ownerOccupied: boolean | null;
  ownerMailingAddress: string | null;
  raw: unknown;
};
